{ pkgs, username, ... }:
{
  environment.systemPackages = with pkgs; [
    libnotify
    wl-clipboard
    hyprpicker
    brightnessctl
    i2c-tools
    ddcutil
    pavucontrol
    pulseaudio
    alsa-utils
    swappy
    swww
    grim
    slurp
    swaynotificationcenter
    wev
    xwaylandvideobridge
    normcap
    ifuse
    libimobiledevice
  ];

  # Extra Portal Configuration
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal
    ];
    configPackages = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal-hyprland
      pkgs.xdg-desktop-portal
    ];
    config.common.default = "gtk";
  };

  # Services to start
  services = {
    usbmuxd = {
      enable = true;
      package = pkgs.usbmuxd2;
    };
    greetd = {
      enable = true;
      vt = 3;
      settings = {
        default_session = {
          user = username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          # command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
          command = "Hyprland"; # start Hyprland with a TUI login manager
        };
        initial_session = {
          user = username;
          command = "Hyprland";
        };
      };
    };
    # to make hyprland / hypridle work
    logind = {
      powerKeyLongPress = "poweroff";
      powerKey = "suspend";
      lidSwitch = "ignore";
    };
    tumbler.enable = true;
    gnome.gnome-keyring.enable = true;
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      jack.enable = true;
    };
  };
  systemd = {
    services = {
      usbmuxd.serviceConfig = {
        # fix shutdown hanging
        TimeoutStopSec = 5;
        KillMode = "mixed";
      };
    };
  };

  # ddcutil
  hardware.i2c.enable = true;

  # Extra Logitech Support
  hardware.logitech.wireless.enable = false;
  hardware.logitech.wireless.enableGraphical = false;

  # Bluetooth Support
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  security.pam = {
    services = {
      hyprlock = { };
    };
  };
}
